### PR TITLE
Fix/sdk issues #398

### LINKED ISSUE #398: SDK issues
`absoluteLink` is redundant in `getLink()` response.
`link` in `getLink()` response should not be hard-coded.

### PR DESCRIPTION
**Pull request by ompharate**
Fixes #398

### CODE REVIEW

File: backend/api/chatLink/index.ts [hunk 1]
```diff
@@ -3,28 +3,29 @@ import express from 'express';
 import db from '../../db';
```
Comment (muke1908) [inline backend/api/chatLink/index.ts:3]: Can you please change the file name as well? `chatHash` and adjust the changes in https://github.com/muke1908/chat-e2ee/blob/master/backend/api/index.ts

**Comment by muke1908** [comment]
Thanks!
